package cn.huafeng.dao;

import cn.huafeng.po.GITpo;

public interface GITpoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table git
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    int insert(GITpo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table git
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    int insertSelective(GITpo record);
}