package cn.huafeng.dao;

import cn.huafeng.dto.UserDto;
import cn.huafeng.po.UserPo;

import java.util.List;

public interface UserPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 02 21:38:05 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 02 21:38:05 GMT+08:00 2018
     */
    int insert(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 02 21:38:05 GMT+08:00 2018
     */
    int insertSelective(UserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 02 21:38:05 GMT+08:00 2018
     */
    UserDto selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 02 21:38:05 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Mon Jul 02 21:38:05 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserPo record);

    //查询所有
    public List<UserDto> query();

    //模糊查询
    public List<UserDto> search(String kw);
}