package cn.huafeng.po;

public class GITpo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column git.name
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column git.sex
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column git.age
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column git.hoby
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    private String hoby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column git.addr
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column git.tel
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    private String tel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column git.name
     *
     * @return the value of git.name
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column git.name
     *
     * @param name the value for git.name
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column git.sex
     *
     * @return the value of git.sex
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column git.sex
     *
     * @param sex the value for git.sex
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column git.age
     *
     * @return the value of git.age
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column git.age
     *
     * @param age the value for git.age
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column git.hoby
     *
     * @return the value of git.hoby
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public String getHoby() {
        return hoby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column git.hoby
     *
     * @param hoby the value for git.hoby
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public void setHoby(String hoby) {
        this.hoby = hoby == null ? null : hoby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column git.addr
     *
     * @return the value of git.addr
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column git.addr
     *
     * @param addr the value for git.addr
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public void setAddr(String addr) {
        this.addr = addr == null ? null : addr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column git.tel
     *
     * @return the value of git.tel
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column git.tel
     *
     * @param tel the value for git.tel
     *
     * @mbggenerated Fri Aug 03 16:36:13 GMT+08:00 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }
}